# Generated by Django 6.0.4 on 2026-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('html_body', models.TextField(help_text='HTML email body. Available variables: {{ full_name }}, {{ email }}, {{ phone }}, {{ location }}, {{ destination }}, {{ travel_date }}, {{ people_count }}, {{ package }}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
    ]
