"""
Django settings for Main project — Sri Narpavi Holidays.

Required packages (install before running):
    pip install mysqlclient Pillow

Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings — unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3x%414atk7$ssg(*8@im@g-h#nv3h!qe4i$uq2a%nq2w)g%+a%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Sri Narpavi Holidays apps
    "apps.core",
    "apps.categories",
    "apps.packages",
    "apps.enquiries",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database — MySQL
# Requires: pip install mysqlclient
# Create the database first: CREATE DATABASE trip_planner_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "trip_planner_db",
        "USER": "root",
        "PASSWORD": "7418022289",  # Update with your MySQL password
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploaded images)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ─── Jazzmin Admin Theme ──────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    # Site title & branding
    "site_title": "SriNarpavi Admin",
    "site_header": "SriNarpavi Holidays",
    "site_brand": "SriNarpavi Holidays",
    "site_logo": "images/logo.png",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "images/logo.png",
    "welcome_sign": "Welcome to SriNarpavi Holidays Admin",
    "copyright": "SriNarpavi Holidays",
    # Search bar
    "search_model": ["packages.Package", "enquiries.Enquiry", "categories.Category"],
    # User avatar
    "user_avatar": None,
    # Top menu
    "topmenu_links": [
        {"name": "Home", "url": "/", "new_window": True},
        {"name": "Packages", "url": "/packages/", "new_window": True},
        {"model": "auth.User"},
    ],
    # Side menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "packages",
        "packages.Package",
        "packages.PackageImage",
        "packages.Itinerary",
        "categories",
        "categories.Category",
        "enquiries",
        "enquiries.Enquiry",
        "enquiries.EmailTemplate",
        "core",
        "core.HeroImage",
    ],
    # Custom icons (Font Awesome 5)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "packages.Package": "fas fa-suitcase",
        "packages.PackageImage": "fas fa-images",
        "packages.Itinerary": "fas fa-map-marked-alt",
        "categories.Category": "fas fa-tag",
        "enquiries.Enquiry": "fas fa-envelope-open-text",
        "enquiries.EmailTemplate": "fas fa-file-alt",
        "core.HeroImage": "fas fa-image",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    # Related modal (FK picker in popup, not new tab)
    "related_modal_active": True,
    # UI tweaks
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": False,
    "default_theme_mode": "light",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
# ──────────────────────────────────────────────────────────────────────────────

# ─── Email (Gmail SMTP + App Password) ────────────────────────────────────────
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "mailforprogram01@gmail.com"
EMAIL_HOST_PASSWORD = "wcxadlraecourouf"  # ← Replace with your Gmail App Password
DEFAULT_FROM_EMAIL = f"Sri Narpavi Holidays <{EMAIL_HOST_USER}>"
ADMIN_ENQUIRY_EMAIL = "sayeerampr0550@gmail.com"
# ──────────────────────────────────────────────────────────────────────────────
