# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional category cover image shown on homepage cards",
                null=True,
                upload_to="categories/",
            ),
        ),
    ]
