# Generated by Django 6.0.4 on 2026-04-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional category cover image (WebP preferred) shown on homepage cards', null=True, upload_to='categories/'),
        ),
    ]
