# Generated by Django 6.0.4 on 2026-04-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text='e.g. 5 Days / 4 Nights', max_length=100)),
                ('group_size', models.CharField(help_text='e.g. 2–10 People', max_length=100)),
                ('language', models.CharField(help_text='e.g. English, Tamil', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Per person price in INR (leave blank if on request)', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='packages.package')),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'ordering': ['day_number'],
            },
        ),
    ]
