# Generated by Django 6.0.4 on 2026-04-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, help_text='Package cover image (WebP preferred)', null=True, upload_to='packages/'),
        ),
    ]
