# Generated by Django 6.0.4 on 2026-04-25 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional package image (WebP preferred)', upload_to='packages/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='packages.package')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
