# Generated by Django 6.0.4 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended: landscape image, at least 1920×1080 px', upload_to='hero/')),
                ('title', models.CharField(blank=True, help_text='Optional caption displayed as alt text (not shown on slide)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
