# Generated by Django 6.0.4 on 2026-04-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(help_text='Recommended: landscape image, at least 1920x1080 px', upload_to='hero/'),
        ),
    ]
